name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - name: Set Up JDK 11
    uses: actions/checkout@v2
    with:
      java-version: '11'
      distribution: 'adopt'
  - name: Buils with Maven
    run: mvn -B -e verify
